### ISSUE TITLE
Tracking issue for multiplayer issues

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu#11250]
# Required before release
- [x] Disconnection should part the room (#11265)
- [x] Retrying should be disabled (also investigate incorrect player state on retry - [gets stuck in playing server-side](https://gist.github.com/peppy/a01dc1d637642fedf4915dfe626818d7)) (https://github.com/ppy/osu/pull/11267)
- [x] Add "playing" state to the user panel (#11252)
- [x] Add leaderboard to multiplayer player (#11253)
- [x] Multiplayer song select isn't applying looping to hold selection (#11254)
- [x] Joining ended games shouldn't be possible (shouldn't send a request in the first place) (#11256)
- [x] Game crashes on exceptions from signalr. Make errors show as notifications. (#11266)
- [x] Changing ruleset after opening a room breaks everything (#11281)

# Nice to have

- [x] Don't send loaded state while notification steals focus (move loading/loaded states to PlayerLoader) (#11279)
- [x] Disable skipping, or make all users skip simultaneously. (#11282)
- [x] Add sounds for state changes and room start (https://github.com/ppy/osu/pull/11283 / https://github.com/ppy/osu/pull/11284)
- [x] Frame bundle should include enough data to show accuracy... accurately (either rolling max score or calculated acc) (https://github.com/ppy/osu/pull/11278)
- [x] Add "Waiting for players" / "Waiting for results" to player/playerloader. (#11279)
- [ ] Don't accept any user inputs in player until gameplay has actually started.
- [x] Server should check whether beatmap is valid in ChangeSettings calls (https://github.com/ppy/osu-server-spectator/pull/16)
- [x] Disable buttons in match subscreen to prevent double actions. (https://github.com/ppy/osu/pull/11353)
- [x] Change "create room" button to "create match", disable while multiplayer client is not connected. (#11274)
- [x] Add states for when the user doesn't have the map / is downloading the map. (https://github.com/ppy/osu/pull/11410)
- [x] If an error occurs at the change settings dialog, all info will be cleared from it rather than reset or left in current state. (https://github.com/ppy/osu/issues/11416)
- [x] If a room is created with a beatmap with mods chosen, they will get discarded after the room is created (need to select the mods twice for it to succeed). (https://github.com/ppy/osu-server-spectator/pull/19)
- [x] Investigate chat being gray in some cases (when using F8 chat) (see existing issue #9508)
- [x] Ready button crashes when deleting beatmap. (https://github.com/ppy/osu/pull/11415)
- [x] Track sometimes loops in player before results are pushed, making the player stuck at a loading spinner. (#11290)
- [x] Ranks aren't showing on participant list. (tracked via https://github.com/ppy/osu-web/issues/7038)
- [x] Multiplayer and playlist rooms both use the "timeshift" game mode (it should probably be nuked).
- [x] Some sort of ready-up countdown (tracking timer tasks via https://github.com/ppy/osu/issues/11367)

**Comment by frenzibyte** [comment]
I'll take:
- Joining ended games shouldn't be possible (shouldn't send a request in the first place)
- Multiplayer song select isn't applying looping to hold selection

**Comment by peppy** [comment]
I'm going to look at adding the "playing" state to panels.

**Comment by peppy** [comment]
I'm going to add the leaderboard to player next.

**Comment by frenzibyte** [comment]
I'm gonna have a look at adding "not downloaded / downloading beatmap state" for the player.

**Comment by peppy** [comment]
Make sure to add ample test coverage for this (in line with existing state change tests, server side)

**Comment by bdach** [comment]
I've noted down a few more things I spotted from today's launch. There'll probably be more.

**Comment by peppy** [comment]
We should probably consider splitting out any remaining issues from this one and close it. Not sure how much help it is post-release.

**Comment by frenzibyte** [comment]
After looking at the ranks issue, it appears to be that `current_mode_rank` doesn't get passed on multiple users lookup requests. 

And either way, `current_mode_rank` isn't actually the correct property for use, if the ruleset changes, the ranks of each participant should update with the current ruleset.

Therefore, there should be some properties or a compact version of `statistics` that has the global ranks for each ruleset. I'll report this API limitation web-side.

**Comment by peppy** [comment]
@bdach i think you added "Don't accept any user inputs in player until gameplay has actually started" - i'm not entirely sure what this relates to, so can you open this as its own issue?

**Comment by peppy** [comment]
Closing this as all issues are tracked (in some form) or completed.
