### ISSUE TITLE
Add support for changing displayed online state

### ISSUE THREAD

**Issue by thymue** [ppy/osu#12635]
**Describe the bug:** Setting your state to "Do not disturb" or "Appear offline" is probably not saved when you exit the game. After restarting it gets set back to "Online".

**osu!lazer version:** 2021.424.0

```[tasklist]
### Tasks
- [ ] https://github.com/ppy/osu-web/issues/10777
- [ ] https://github.com/ppy/osu/pull/25693
- [ ] https://github.com/ppy/osu/pull/25694
- [ ] https://github.com/ppy/osu-server-spectator/pull/202
```

**Comment by peppy** [comment]
As a heads up, this function doesn't actually do anything either. Was one of the earlier implementations that was UI first (before underlying functionality existed).

**Comment by peppy** [comment]
I'm adding this to the project as I think it's quite important. This needs to be handled by either `osu-web` or `osu-spectator-server`, and handle updating the user's last online time.

**Comment by peppy** [comment]
I think to close this out, we just need to store the last online state the config?

**Comment by peppy** [comment]
@bdach are you interested in adding the storage to config? should just store the user's last state so that they can set it immediately on connect. might need some consideration to make sure it's set immediately as part of the connection process (so an "appear offline" user doesn't bounce online for a few milliseconds), but if that's too high effort that can come later with a separate tracking issue.

**Comment by bdach** [comment]
Yes it has been on my radar I just didn't get around to it due to _vaguely points at everything else going on_

**Comment by bdach** [comment]
Has been resolved for a while now.
