### ISSUE TITLE
Options meta issue

### ISSUE THREAD

**Issue by SirCmpwn** [ppy/osu#127]
## Options Handling

Things that need doing around maintaining your settings:

* [x] Loading/configuration
  * [x] Defaults
  * [ ] Dependent options - WIP
* [x] UI - WIP
  * [x] Options sections
  * [x] Jump to section sidebar
  * [x] Sidebar expands on hover like old osu
  * [x] As you scroll, the nav should get updated
  * [x] Animate the pop in of the panel and the sidebar seperately
* [x] UI wired up to bindables
  * [x] booleans (checkboxes)
  * [x] strings (text boxes)
  * [x] enums (dropdowns)
  * [x] numbers (sliders)
* [x] Deal with overlay clicky issues on desktop
* [x] Rework options a bit for osu!next (some categories could be reworked)
* [x] Tooltips
* [x] Logging in
* [x] Hide or show relevant settings based on platform
* [ ] Offset wizard
* [ ] Keybindings
  * [ ] osu!mania layout
* [ ] Skin stuff
* [ ] Maintenance options
* [ ] Per-user options

**Comment by SirCmpwn** [comment]
Settings whose values are wired up to behavioral changes:

* [ ] Prefer unicode display
* [ ] Alternative chat font
* [ ] Release setream
* [ ] FPS counter
* [ ] Reduce dropped frames
* [ ] Detect performance issues
* [ ] Resolution
* [ ] Fullscreen mode
* [ ] Letterboxing
  * [ ] Position
* [ ] Snaking sliders
* [ ] Background video
* [ ] Storyboards
* [ ] Combo bursts
* [ ] Hit lighting
* [ ] Shaders
* [ ] Softening filter
* [ ] Screenshot format
* [ ] Menu snow
* [ ] Menu parallax
* [ ] Menu tips
* [ ] Interface voices
* [ ] osu! music theme
* [ ] Show thumbnails in song select
* [ ] Background dim
* [ ] Progress display
* [ ] Score meter type
* [ ] Score meter size
* [ ] Always show key overlay
* [ ] Show approach circle on first hidden object
* [ ] Scale osu!mania scroll speed with BPM
* [ ] Remember osu!mania scroll speed per beatmap
* [ ] Song select beatmap star slider
* [ ] Audio output device
* [ ] Volume
* [ ] Ignore beatmap hitsounds
* [ ] Universal offset
* [ ] Selected skin
* [ ] Ignore beatmap skins
* [ ] Use skin sound samples
* [ ] Use Taiko skin
* [ ] Use skin cursor
* [ ] Cursor size
* [ ] Auto cursor size
* [ ] Mouse sensitivity
* [ ] Raw input
* [ ] Map raw input to window
* [ ] Confine mouse cursor
* [ ] Disable mouse wheel
* [ ] Disable mouse buttons
* [ ] Cursor ripples
* [ ] Keybindings
* [ ] OS Tablet support
* [ ] Wiimote support
* [ ] Editor background video
* [ ] Editor default skin
* [ ] Editor snaking sliders
* [ ] Editor hit animations
* [ ] Editor follow points
* [ ] Editor stacking
* [ ] Filter offensive words
* [ ] Filter foreign characters
* [ ] Log PMs
* [ ] Block non-friend PMs
* [ ] Chat ignore list
* [ ] Chat highlight list
* [ ] Share city location
* [ ] Allow any multiplayer invites
* [ ] Enable chat ticker
* [ ] Show notification popup on highlight
* [ ] Show chat notifications
* [ ] Audible highlights
* [ ] Notifications during gameplay
* [ ] Friend status changes
* [ ] Yahoo integration
* [ ] MSN Live integration
* [ ] Auto start osu!direct
* [ ] osu!direct prefer no-video

**Comment by peppy** [comment]
Closing this one for now. Let's recreate settings issues in a milestone rather than using a huge flat-list.
