### ISSUE TITLE
Missing sound effects

### ISSUE THREAD

**Issue by peppy** [ppy/osu#14082]
In an interest of hopefully helping @nekodex  with remaining coverage, here's some sound effect related holes that came up during a play session:

- [x] ~Opening a context menu~ #14148
- [x] ~Clicking between panels at the results screen~ #19300
- [x] ~Entering results screen from song select (feels underwhelming / wrong with just the click)~  #19300
- [x] ~Random select (should probably have its own card flicky sound or similar)~ #16675
- [x] ~Multiplayer games list (only plays sound for the selected panel)~ #14147
- [x] ~Joining a multiplayer room~ #14147
- [x] ~Clicking into and selecting text in a textbox~ #19850
- [x] ~Dragging list items around~ #18818
- [x] ~Mod select screen (appearance sound)~ #18970
- [x] ~Metronome (currently placeholder, add locking sound?)~ #18744

**Comment by Gabixel** [comment]
(I guess it makes sense to post this here instead of creating another issue.)
I would suggest adding a "switch" sound when switching between chats with the keyboard shortcut (<kbd>CTRL</kbd> + <kbd>TAB</kbd>). Currently, only the "click" sound plays when switching (ignoring whether you used the mouse or the keyboard):

https://user-images.githubusercontent.com/43073074/128695672-4b22f59a-9600-4680-a77e-d09791170b6b.mp4

I'm 50% sure that it could be different for keyboard users (but my other 50% thinks that it's not *that* wrong).

**Comment by Theighlin** [comment]
Other sounds that are missing in comparison to stable are in a multi lobby the ready/unready state change, the change of map and when you're given host. Plus the spectate button could use one too and one when the map ends for someone waiting in an already started lobby would be useful.

**Comment by peppy** [comment]
> Other sounds that are missing in comparison to stable are in a multi lobby the ready/unready state change, the change of map and when you're given host. Plus the spectate button could use one too and one when the map ends for someone waiting in an already started lobby would be useful.

To confirm, you mean the "host" changing their ready state? Other users already has a sound effect (although it was made much softer by @nekodex sample changes, I believe..)

**Comment by Theighlin** [comment]
> To confirm, you mean the "host" changing their ready state? Other users already has a sound effect (although it was made much softer by @nekodex sample changes, I believe..)

I just checked, the player changing ready state button (user as well as host) has a sound, but what i originally meant is that it should have a more distinct one like in stable and not be the same as all other buttons (could have been the skin that made it different but it should be there also on default one if not).

I'll recap my previous comment and add a couple of things here

- When changing state to ready and not ready (2 different sounds)
- When clicking spectate button? (idk about this one, sounds cool to me but then maybe every button in the game would end up having a different sound)
- When a beatmap is changed
- When you're given host
- When players join and leave the room
- When gameplay ends so to alert users waiting in lobby.
- Changing room match type (could have different sounds like changing ruleset imo)

https://user-images.githubusercontent.com/53081750/128917923-de8bd9bb-eeef-41b2-920b-216ecbe39580.mp4

**Comment by Gabixel** [comment]
As per a recent post (#20099, which I will transfer here), textboxes don't play any sound when cleared with the <kbd>Esc</kbd> key:

https://user-images.githubusercontent.com/43073074/188123904-28d5f75a-b726-4387-b12d-91099c3f7c85.mp4

The sound that is played when deleting a character could be appropriate for this.

**Comment by peppy** [comment]
- Binding keyboard bindings doesn't play any sound and probably should (as noted by pishifat in https://youtu.be/xOXYFfw0KZM?t=171)

**Comment by bdach** [comment]
@nekodex in light of today's catch-up shall I take it that you've run out of things on this list and this can maybe be closed?

**Comment by nekodex** [comment]
Hmm, maybe it's best to close this for now and direct people to create standalone issues for anything new that comes up?

**Comment by bdach** [comment]
Sounds like a plan
