### ISSUE TITLE
Implement robust beatmap invalidation / update flow

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18665]
A very important feature that is absolutely required for any kind of mass lazer adoption is keeping beatmaps up-to-date as they change server-side, and also ensuring that any local modifications mean the beatmap is invalidated for leaderboard submission purposes.

Covers work to ensure that:

- [x] When saving a beatmap it is correctly invalidated for ranking, recomputed for difficulty calculation etc. (https://github.com/ppy/osu/issues/11922, https://github.com/ppy/osu/issues/17676)
- [x] When difficulty calculation changes are made, beatmaps should be queued for reprocessing (https://github.com/ppy/osu/issues/10242)
- [x] When importing a beatmap that's already imported, ensure the newly imported beatmap can overwrite the existing (or import alongside) (https://github.com/ppy/osu/issues/18600)
- [x] When a beatmap is updated server-side, it should prompt the user with the ability to update the beatmap (https://github.com/ppy/osu/issues/2425, https://github.com/ppy/osu/issues/4823, https://github.com/ppy/osu/discussions/16467 etc.) 
   - Stretch: A setting to always keep beatmaps up-to-date may also be nice to have.

**Comment by peppy** [comment]
There's probably some related issues that I haven't linked in here, so please shout out any that people can remember (cases where SR or dates are not updated correctly, or anything related to beatmaps being out-of-date).

**Comment by Theighlin** [comment]
> (cases where SR or dates are not updated correctly, or anything related to beatmaps being out-of-date).

This one #10242?

**Comment by peppy** [comment]
Providing more details on the overall picture of how I am going forward with this:

Currently, the client already has a database of all online metadata (see `BeatmapOnlineLookupQueue`) in a sqlite database. This is downloaded once on first startup and never updated.

Going forward
- This data should be mutable 
- The sqlite dependency should be removed (either move to main realm or secondary realm, probably the latter)
  - This is the only usage of sqlite outside of EF and I'd like to remove it everywhere for simplicity
- This feed should be updated on startup with all changes since the last startup. Would hopefully be a websocket feed to provide very immediate changes.
- During this update, local beatmaps and sets should be compared and at a set level, should be marked `IsDirty` if they don't match the server. This will allow for better tracking if a `BeatmapSet` needs an update without checking each difficulty.
  - As a next step, this update process would also either automatically update beatmaps for a user, or prompt them with the option to do so, based on user preference.

The `IsDirty` flag can also be set when a discrepancy is detected, ie. in the case of https://github.com/ppy/osu/issues/18600, where `OnlinePlayBeatmapAvailabilityTracker` notices that a `BeatmapInfo`'s hash is not correct but at a `BeatmapDownloadTracker` level is unaware, meaning the user can't click the download button again.

**Comment by peppy** [comment]
`SignalR` is what i was planning, yes. The bootstrap download will still be a thing though, because it will increase efficiency greatly.

**Comment by peppy** [comment]
As an update, the first portion of this will go live with the next release (the flow of metadata updates from client-server). Current work is progressing on storing the state of beatmaps client side, so the game can update or prompt the user to update when new versions are available.

**Comment by peppy** [comment]
With #19230, the majority of the "update due to online changes" is done.

Remaining points of concern:
- https://github.com/ppy/osu/issues/2425 is mentioned in the opening post, but seems quite unrelated to this issue. I'll be looking into this since it's an easy one to add.
- Handling the case of difficulty algorithm changes. This will likely require "targeted" updates in `BeatmapUpdater`, ie. splitting out whether we have queued an update for difficulty calculation or online metadata (or something else). I'll address this as a follow-up once the beatmap update flow has settled to avoid piling changes.
