### ISSUE TITLE
Add anti-cheat flow

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18876]
Will track internal work on this task

- [x] Review existing token flow
- [x] Deploy server components
- [x] Add remaining implementation
- [ ] Taikomania etc

**Comment by smoogipoo** [comment]
Closing as this has now been done and the heuristics can/will be updated in the future (doesn't deserve task list/issue).
