### ISSUE TITLE
Song select design and UX pass

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18890]
- [ ] Add missing pieces like sort-by-difficulty (ungrouped).

### Tasks
- [ ] Skinning editor support
- [ ] Modular difficulty settings

**Comment by Gabixel** [comment]
Related issues:
- #5390
- #2547
- #4919

**Comment by NullifiedJosh** [comment]
Hmm, this design looks a bit cluttered to me.
