### ISSUE TITLE
Add ability to submit beatmaps to BSS

### ISSUE THREAD

**Issue by peppy** [ppy/osu#18901]
Covers the ability to submit beatmaps to online systems for sharing with others.

- [x] https://github.com/ppy/osu-server-beatmap-submission/issues/2
- [x] https://github.com/ppy/osu/pull/31733
- [x] https://github.com/ppy/osu/pull/31734
- [x] https://github.com/ppy/osu/pull/31747
- [x] https://github.com/ppy/osu/pull/31783
- [x] https://github.com/ppy/osu/pull/31784
- [x] https://github.com/ppy/osu/pull/31803
- [x] https://github.com/ppy/osu/pull/31804
- [ ] https://github.com/ppy/osu/pull/31805

**Comment by bdach** [comment]
For interested parties, server-side development is taking place at https://github.com/ppy/osu-server-beatmap-submission.
