### ISSUE TITLE
Timing: Reassess "platform specific" audio offset

### ISSUE THREAD

**Issue by peppy** [ppy/osu#24625]
A platform offset of ~~24ms~~ 15ms is applied, currently only on windows. This is intended to match osu!stable, which originally added this to fix BASS reporting current time with an unexpected offset (this was potentially fixed at bass' end when switching from DirectAudio to WASAPI, but still exists as it resulted in the offset being baked into beatmaps).

As I mentioned [here](https://github.com/ppy/osu/issues/21947#issuecomment-1550847864), this probably needs to be applied to all platforms instead.

We should also quadruple confirm this is implemented correctly, especially in flows of

- Gameplay
- Replay playback
- Actually getting the correct playback offset from BASS on all platforms
- Check special cases in legacy decode/encode processes

There are some other related issues, but I'm opening a fresh one to track this as I believe we want to be sure that everything is okay before we get scoring online. It would suck if we started to persist replays with incorrect timing, for instance.

Task list includes all relevant issues, including rate adjust causing incorrect offset application.

```[tasklist]
### Tasks
- [ ] https://github.com/ppy/osu/issues/20293
- [ ] https://github.com/ppy/osu/issues/24015
- [ ] https://github.com/ppy/osu/issues/21947
- [ ] https://github.com/ppy/osu/issues/18909
- [ ] https://github.com/ppy/osu/issues/10646
```

**Comment by longnguyen2004** [comment]
Will this mean that lazer will also have the same wrong offset issue as stable? At least for the couple maps I've tested, lazer and Quaver are having the correct offset relative to the song file. If any offset changes were to be applied, it shouldn't affect the waveform.

Map in question if you want to investigate: https://osu.ppy.sh/beatmapsets/1509132#mania/3253011
Offset on this is correct relative to waveform, so whatever offset changes applied shouldn't affect it.

**Comment by peppy** [comment]
The goal is to make things match how they should be. I can't really give more information than that.

Right now we don't really need feedback on this issue. It requires investigation by a developer who has knowledge of historical offsets in osu!'s past.

**Comment by peppy** [comment]
In the last few days I've reassessed the global offset, and it still seems somewhat correct. Also, at least for me, having 0ms offset on macOS is better than applying the 15ms. I can't say the same about linux, but for now I don't think there is anything actionable here. Will revisit at a later date next year.
