### ISSUE TITLE
Gameplay / audio timing falls short of expectations in several ways

### ISSUE THREAD

**Issue by peppy** [ppy/osu#24811]
This is an issue tracking remaining timing concerns. I've grouped this together as I intend to take on all these tasks myself, and they are all likely going to be inter-related (and require changes to the clock setup).

```[tasklist]
### Tasks
- [ ] https://github.com/ppy/osu/issues/24015
- [ ] https://github.com/ppy/osu/issues/23149
- [ ] https://github.com/ppy/osu/issues/24625
```

**Comment by bdach** [comment]
@peppy is https://github.com/ppy/osu/issues/22488 something we want to include in the task list here?

**Comment by peppy** [comment]
Sure.

**Comment by peppy** [comment]
Closing this one out. I'll continue to track #22488 and revisit when i revisit wasapi stuff. It's the same as stable so this can remain in plaace a bit longer.
