### ISSUE TITLE
osu!taiko playfield sizing doesn't match

### ISSUE THREAD

**Issue by peppy** [ppy/osu#25937]
https://osu.ppy.sh/community/forums/posts/9372074

```[tasklist]
### Tasks
- [ ] https://github.com/ppy/osu/pull/26631
- [ ] https://github.com/ppy/osu/pull/26632
- [ ] https://github.com/ppy/osu/pull/26634
- [ ] https://github.com/ppy/osu/pull/26635
```

**Comment by bdach** [comment]
https://github.com/ppy/osu/issues/25919?
https://github.com/ppy/osu/issues/25862?

**Comment by peppy** [comment]
I'm not sure if they are related, but might be. There have been reports of both the size/position being off, and the default speed being off. I'd rather track separately until we know that they are related.

**Comment by bdach** [comment]
Sure, was more intended as a backlink to verify all threads there when looking at this.

**Comment by frenzibyte** [comment]
This has long been resolved.
