### ISSUE TITLE
Depth mod doesn't work online

### ISSUE THREAD

**Issue by bdach** [ppy/osu#26195]
Gonna pre-empt inevitable reports of this

```[tasklist]
### Tasks
- [ ] https://github.com/ppy/osu-web/pull/10838
- [ ] https://github.com/ppy/osu-server-spectator/pull/207
- [ ] deploy of both above
```

**Comment by Joehuu** [comment]
Has since been fixed:

![Screenshot 2024-01-09 at 9 44 13 PM](https://github.com/ppy/osu/assets/35318437/60e4f189-9aa7-4860-b5fb-9a8a41cc972e)
