### ISSUE TITLE
master todo list

### ISSUE THREAD

**Issue by peppy** [ppy/osu#285]
This is an overall view at what is left to complete functionality of the osu! client, prioritised to make it adoptable by users as soon as possible.

- [x] Fix black screen DI bug
- [ ] Touchscreen/tablet support
- [x] Player
    - [x] Failing
    - [x] HP Bar
    - [x] Slider ticks (osu!)
    - [x] Full hitsound support
    - [x] Spinners (osu!)
    - [x] Follow points (osu!)
    - [x] Stack leniency (osu!)
    - [x] Progress display
    - [x] Pause screen
- [x] Results screen
- [ ] Chat support
    - [x] Reading messages
    - [x] Tab control implementation (framework?)
    - [x] Join/quit channels
    - [x] Sending messages
    - [ ] Private message support (temporary?)
- [x] Options wiring
- [ ] osu!direct
- [ ] Song select
    - [ ] Performance optimisation for large collections
    - [x] Search
    - [x] Sorting (basic logic complete, UI not so much)
    - [ ] Grouping (basic logic complete, UI not so much)
    - [x] Scoreboards
    - [x] Mod select
- [x] osu!taiko
- [ ] osu!catch
- [ ] osu!mania
- [x] Replay playback
- [ ] Multiplayer
- [ ] Editor
- [ ] Collections support (music control, song select)

**Comment by Osuology** [comment]
I suspect the other game modes will take the longest. If you were to give a date on when you think this will all be finished, when would you say peppy?

**Comment by WolfHD** [comment]
good luck lol

**Comment by Tom94** [comment]
We now have failing support thanks to https://github.com/ppy/osu/pull/290 and a pause screen thanks to https://github.com/ppy/osu/pull/301 . We also have basic search functionality in song select by https://github.com/ppy/osu/pull/299 .

**Comment by peppy** [comment]
spinners done #358 
slider ticks almost in #359 
follow points in #342 
stacking in #336

**Comment by Tom94** [comment]
We now have rudimentary replay playback, taiko, scoreboards, mod select, and sorting in song select.

**Comment by peppy** [comment]
Marking off "full hitsound support" since @smoogipooo fixed that up last week. We are still missing skin/beatmap customisation, but the base hitsounds should be 1:1 now.

**Comment by Nugamus420** [comment]
@peppy You should add sending messages as you managed to get that into the build

**Comment by peppy** [comment]
🆗 results screen (partial but enough)
🆗 sending messages in chat

**Comment by Nugamus420** [comment]
🆗 peppy is now loli

@peppy

**Comment by peppy** [comment]
- marking chat tabs as complete.
- marking options wiring as complete (all visible options are now wired; we'll add as we go).

**Comment by lunafreya** [comment]
OK then, since this to-do list covers every basic feature of the new osu! client needed for even an alpha-scale adoption, I think we should reword this issue more clearly e.g. (my suggestion) "Master to-do list (high priority)". That way, another to-do list (for the new osu! client's other low-prio stuff) can be made.

**Comment by peppy** [comment]
"another" to-do list is not necessary.

**Comment by peppy** [comment]
Superseded by #988.
