### ISSUE TITLE
GameMode improvements worklist

### ISSUE THREAD

**Issue by smoogipooo** [ppy/osu#480]
To keep things more organized on my end I am creating a worklist of issues which I will be addressing before resuming my work on game modes. Ticks represent if the task has been merged.

- [x] **(COMPLETE)** Hide away the HUD (will be skinnable in the future).
- [x] **(Complete)** Rework Beatmap conversion to provide generic HitObjects.
- [ ] **([WIP](https://github.com/ppy/osu/issues/475))** Mode-specific Beatmap parsers should be provided basic HitObjects to extract properties out of.
- [ ] **([WIP](https://github.com/ppy/osu/issues/476))** Re-implement and generalize mod application and removal.
- [ ] **([PENDING](https://github.com/ppy/osu/issues/477))** Remove PlayMode enum.
- [ ] **([PENDING](https://github.com/ppy/osu/issues/478))** General ScoreProcessor rework and improvements.
- [ ] **([PENDING](https://github.com/ppy/osu/issues/479))** (Re-)Implement HitObject samples (banks, additions, etc).
