### ISSUE TITLE
Improve iOS file system

### ISSUE THREAD

**Issue by dtsdao** [ppy/osu#5545]
Things to be done:

- [x] ~~In #5533 I made a mistake. Opening osu! files makes osu! crash. I'll fix it.~~ Finished.

- [ ] ~~Since it will auto backup files to iCloud, it's better to use `/Library/Document/` instead of `/Document/`.~~ Unnecessary

- [x]  ~~Then the document directory can be empty, so we can use it to import files. Like #5485 and #5272. Just use "Import from stable" is fine. And we can create a directory (like "Inbox") to accept zipped files.~~ Finished. Just drag and drop your directories from stable to iTunes and you can import them in osu!lazer

- [x] ~~Maybe just one line in `Info.plist` can solve #5274.~~ Finished. Tons of changes.

Creating for visibility. PR welcome to my fork.

**Comment by dscnnctd** [comment]
Will this also include fix for missing "Copy to" option for iOS 13?

**Comment by dtsdao** [comment]
> Will this also include fix for missing "Copy to" option for iOS 13?

Get the newest TestFlight version that is 2019.730.0 would solve it. Just update in TestFlight.

It works well on iOS 12 and should be compatible on iOS 13.

But importing causes crashes (at least on my iPad) as I mentioned in Problem 1.

You can test it and feedback here.

**Comment by dscnnctd** [comment]
> > Will this also include fix for missing "Copy to" option for iOS 13?
> 
> Get the newest TestFlight version that is 2019.730.0 would solve it. Just update in TestFlight.
> 
> It works well on iOS 12 and should be compatible on iOS 13.
> 
> But importing causes crashes (at least on my iPad) as I mentioned in Problem 1.
> 
> You can test it and feedback here.

It’s completely missing, no matter what file type it is (.osk/.osr/.osz).
![5974308F-69C4-4A4A-BFD7-490508796CF7](https://user-images.githubusercontent.com/48611569/62209139-fd03fd80-b355-11e9-8d1c-3e9f78f8fcbb.jpeg)
![5C8793A4-2B0A-4316-8A2D-5217F7F61D30](https://user-images.githubusercontent.com/48611569/62209140-fd03fd80-b355-11e9-9a11-6ecd250b10ad.png)

**Comment by dtsdao** [comment]
This is weird. Maybe sth is wrong in `Info.plist`. Added to my project.

**Comment by dtsdao** [comment]
@dscnnctd Take a look. It seems to be a bug in iOS13.

https://forums.developer.apple.com/thread/118932

By the way, could you test importing files on iOS12?

I'm not sure if Problem 1 only happens on my device.

**Comment by dscnnctd** [comment]
I see, thanks. I will also test it out later in the afternoon.

**Comment by dscnnctd** [comment]
I did some testing today and yes, it does crash. I’ve tested different supported file types multiple times, and they all seem to crash. I managed to get a skin imported before _2019.730.0_ though.

**Comment by jraspiprojects** [comment]
Sort of related, where does osu! look for beatmaps on iOS?

**Comment by swoolcock** [comment]
It doesn't.  Beatmaps are stored in a database the same way as Lazer on desktop.
