### ISSUE TITLE
Use new automatic state logic for all rulesets

### ISSUE THREAD

**Issue by iiSaLMaN** [ppy/osu#5841]
Currently, rulesets other than osu! use the legacy `UpdateState()` function.

- [x] Taiko ruleset (see #5848)
- [x] Catch ruleset (see #5842)
- [x] Mania ruleset (see #5844)
