### ISSUE TITLE
Taiko todo

### ISSUE THREAD

**Issue by smoogipooo** [ppy/osu#597]
- [x] 1: Debug performance on hits (especially drum roll hits).
  * Visible on the first drum roll of https://osu.ppy.sh/b/235879&m=0
- [x] 2: Major barlines are off by one index,
- [x] 3: Converts are wrong on https://osu.ppy.sh/b/235879&m=0.
  - [x] 3.1: Nodal hit sounds aren't being properly considered for drum roll -> hitcircle conversion.
  - [x] 3.2: Conversion from drum rolls to hits doesn't take into account sample set.
- [x] 4: Player is being triggered onCompletion too early (likely due to strong hits).
  * Fix onCompletion vs onFailed (should be onCompletion(bool failed) or something like that).
- [x] 5: Make drum rolls shake.
- [x] 6: Add glow to HP bar.
- [x] 7: Drum roll ticks should be smaller.
- [x] 8: Drum roll ticks should not show miss judgement texts
- [x] 9: Implement difficulty calculation.
- [x] 10: Fix Swells being hit too slowly.

**Comment by smoogipooo** [comment]
Apparently #4 isn't a problem anymore.

**Comment by smoogipooo** [comment]
Completed. Closing.
