### ISSUE TITLE
Beatmap Editor (osu!)

### ISSUE THREAD

**Issue by peppy** [ppy/osu#6686]
This issue tracks the remaining tasks to be completed to have the beatmap editor in a roughly usable state (feature parity with `osu-stable`). A few caveats:

- This excludes the design mode (storyboarding support) as that will be tracked as a separate task.
- This focuses on completion of the osu! ruleset editor. Other rulesets will follow afterwards.
- This is a working document and will be updated as issues are created / completed.

# General

- [ ] Add welcome screen when entering editor from main menu

# Timeline

- [x] Add timeline display of hitobjects
- [ ] Add timeline display of control points

# Compose screen

- [x] #6755 Add ability to change / add hitsounds
- [ ] Add clock smooth seeking when moving objects in time
- [x] #6744 Add double clock seeking
- [x] #6733 Deleting hitobjects sometimes causes exceptions
- [x] #6734 Placing distance snapped objects should advance current time

## osu! specific

- [x] #5845 Add "perfect" slider placement type
- [x] #6739 Ability to add control points to existing sliders
- [x] #6681 Fix follow points not updating
- [x] #2646 #6594 Limit placement/movement bounds to inside the playfield
- [x] #6730 Limit snapping bounds to between hitobjects
- [ ] #5538 Fix slider placement causing GL crashes

# Timing screen

- [ ] Update UI elements to conform to one style
- [ ] Add ability to change offset of control points
- [ ] #6793 Add "tap for bpm"

# Setup screen

- [ ] Implement "V2" UI components described in https://github.com/ppy/osu/issues/2434

# Import / Export

- [x] #7531 Support saving of beatmaps (legacy format?)

**Comment by mcendu** [comment]
Is this issue still maintained?

**Comment by smoogipoo** [comment]
yes

**Comment by peppy** [comment]
Closing for now (replaced by https://github.com/ppy/osu/projects/2).
