### ISSUE TITLE
Mania TODO

### ISSUE THREAD

**Issue by smoogipooo** [ppy/osu#705]
Very broad worklist of items to do for osu!mania implementation. Arranged in roughly chronological order.

- [ ] 1: Playfield
- [ ] 2: Notes
- [ ] 3: Hold notes
- [ ] 4: Score processing + judgements.
- [ ] 5: Timing sections (and place notes + bar lines inside them)
- [ ] 6: Beatmap conversion (old algorithm)
- [ ] 7: Auto replay generation
- [ ] 8: Bar lines
- [ ] 9: Legacy replay playback
- [ ] 10: Sample files
- [ ] 11: New designs (@arflyte)
- [ ] 12: Split stages (10K+)
