### ISSUE TITLE
Better offline support

### ISSUE THREAD

**Issue by bdach** [ppy/osu#7417]
Opening as an epic issue to group together other outstanding issues.

There are a few places where offline isn't supported in the best way (blank overlays, endless spinners...) Below is a (currently non-exhaustive) list of known issues associated with being offline:

- [x] Loading animations not stopping (#933)
- [x] Non-functional chat (#3024)
- [x] Non-functional direct (#4550)
- [x] Non-functional changelog (reported as crashing in #7416, crashes no longer)
- [x] Non-functional room browser (#8803)

Latest general direction seems to be [blocking access to online-only views if possible](https://github.com/ppy/osu/issues/933#issuecomment-308322500) and [displaying placeholder text similar to leaderboards if not](https://github.com/ppy/osu/issues/4550#issuecomment-530269254), but that might have changed in the meantime so I'd appreciate corrections if it has.

**Comment by mcendu** [comment]
I am not sure why we use epic issues instead of enabling projects.

**Comment by peppy** [comment]
Projects are useful for a standard agile flow, which this is not.

**Comment by Game4all** [comment]
Should all online overlays which require the user to be logged in exhibit this same behaviour ? If yes, logic could certainly be abstracted in a shared overlay class.

**Comment by iiSaLMaN** [comment]
Regarding the implementation of this, I have an idea that could work out and hopefully make offline support pretty straightforward for upcoming online API components, by implementing a container that handles whether to show the content or the login placeholder:
```
SomeAPIComponent:
    OnlineContainer:
        Box

// Box will show up if user is logged in, else the placeholder (implemented inside OnlineContainer) will show up.

**Comment by peppy** [comment]
Closing this as all of the relevant issues have been addressed via PRs or are covered via other issues.
