### ISSUE TITLE
osu!client to-do list

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu#988]
A top-level overview of what is left to be completed for the new osu!client. Still a WIP, which means there's stuff to add which hasn't been added, but also potentially out-of-date items which need to be updated.

While this issue will exist for now, I plan on exploding each of these tasks into individual issues, so we can tackle (and discuss) them in a more optimal manner.

## Main Menu

- [x] Button system

### Taskbar

- [x] Logging system
- [x] Game Mode selection buttons
- [x] Home and Option buttons
- [x] Notifications system
- [x] Chat related buttons

## Game Modes

- [x] Implementation of Difficulty values
  - [x] AR
  - [x] CS
  - [x] HP
  - [x] OD
- [x] Accuracy formula
  - [x] osu!
  - [x] osu!taiko
  - [x] osu!mania
  - [x] osu!catch
- [x] Score formula
  - [x] osu!
  - [x] osu!taiko
  - [x] osu!mania
  - [x] osu!catch
- [x] Kiai Time
- [x] Slider Velocity
- [x] Game Mode converters
- [x] Offset
- [ ] Combo bursts
- [ ] Achievement triggers
 
### osu!

- [x] Hit Object implementation
  - [x] Circles
  - [x] Sliders
    - [x] Slider ticks
  - [x] Spinners
    - [x] SPM Meter
- [x] Follow Points
- [x] Stack Leniency
- [x] Overall

### osu!taiko

- [x] Special Health Bar (kinda?)
- [x] Playfield (Slider)
- [x] Hit Object implementation
  - [x] Circles
  - [x] Drumrolls
  - [x] Spinners (Dendens)
- [x] Hit Overlay
- [x] Overall

### osu!catch

- [x] Catcher
- [x] Dash
  - [x] Hyperdash
- [x] Hit Object implementation
  - [x] Fruits
  - [x] Juice Drops
  - [x] Droplets
  - [x] Bananas
  - [x] Hyperfruits
- [x] Playfield
- [x] Overall

### osu!mania

- [x] Hit Object implementation
  - [x] Notes
  - [x] Holds
- [x] Judgement Line
- [x] Playfield
- [x] Overall

## Multiplayer

- [ ] Lobby
  - [x] Sorting buttons
  - [x] Search bar
  - [ ] Quick Join
  - [x] Game creation system
     - [ ] Maintenance options
  - [x] Room Drawables
- [x] Multiplayer Room Inspector
  - [x] Mod selector
  - [ ] User Management (e.g. kicking)
  - [x] Beatmap selector
  - [ ] Team Modes
  - [ ] Win Conditions
- [x] Tournament Team Drawer

## Chat

- [x] Channel selection
- [x] Quiting channels
- [x] Joining channels
- [ ] Command support
- [ ] Markdown support
- [x] URL Parsing
- [ ] Changing order of channel tabs
- [x] Private messaging
- [x] Reading and sending messages (kinda)
- [x] Shortened links
- [x] Local chat echo

## Options

- [x] Search bar
- [x] Section selector
- [x] UI elements
  - [x] Checkboxes
  - [x] Text boxes (probably?)
  - [x] Dropdowns
  - [x] Sliders
- [ ] Wired options (mostly from old client)
- [x] OSD for global options
- [ ] Skin Preview
- [ ] Offset Wizard
- [x] osu!mania layout
- [x] Keyboard bindings
- [x] Touchscreen/Tablet support

## Music Controller

- [ ] Collection support
- [x] Ability to change the order of songs
- [x] Clock for Music played
- [x] Search bar

## Song Selection

- [x] Mod selection
- [x] Search bar 
- [ ] Collection support
  - [x] Performance optimisation for large collections
- [x] Sorting (UI done)
- [ ] Grouping (UI done)
- [x] Scoreboards
   - [x] Local
   - [x] Global
   - [x] Country
   - [x] Friends
   - [x] Mods
- [x] Beatmap Info
- [x] Beatmap selection
- [x] Random Beatmap button
- [x] Beatmap options (not wired fully; UI done)
- [x] Results screen

## Mods

- [ ] Easy
  - [x] osu!
  - [ ] osu!taiko
  - [ ] osu!mania
  - [ ] osu!catch
- [x] No-Fail
- [x] Half Time
  - [x] Daycore
- [ ] Hard Rock
  - [x] osu!
  - [ ] osu!taiko
  - [ ] osu!mania
  - [ ] osu!catch
- [x] Sudden Death
  - [x] Perfect
- [x] Double Time
  - [x] Nightcore
- [ ] Hidden
  - [x] osu!
  - [ ] osu!taiko
  - [ ] osu!mania
  - [ ] osu!catch
- [x] Flashlight
  - [x] osu!
  - [x] osu!taiko
  - [x] osu!mania
  - [x] osu!catch
- [ ] Fade In
- [x] Relax
  - [x] osu!
  - [ ] osu!taiko
  - [ ] osu!mania
  - [x] osu!catch
- [ ] Gravity
- [ ] Autopilot
- [ ] Spun-out
- [x] Auto
- [ ] Cinema
- [x] Key Mods (osu!mania)
- [ ] Co-op
- [x] Random
- [ ] Target Practice

## osu!direct

- [x] Search bar
- [x] Sorting buttons (not wired?)
- [x] Wired with Notification system (?)
- [x] Changing Beatmap showing style (List, Tiles)
- [x] Beatmap Status dropdown (not wired?)
- [x] Game Mode selector (not wired?)

## osu!editor

- [ ] Song Selection
  - [ ] Drag&Drop information box
  - [ ] Featured Artists link
- [ ] Timelines
  - [x] Playback Rate
  - [ ] Percentage Progress
  - [x] Music control buttons
- [x] Top menu 
- [ ] Help menu
- [ ] Compose
  - [ ] Hit Sound buttons
  - [x] Hit Object buttons
  - [x] Hit Object Timeline
  - [ ] Break Time inserting
  - [x] Beat Snap Divisor
  - [x] Distance Snap
  - [ ] Locking Notes
  - [x] Workfield
- [ ] Design
  - [ ] Sprite Library
  - [ ] Storyboard Timeline
  - [ ] Workfield
  - [ ] Layer Toggles
  - [ ] Transformations
  - [ ] Easing
  - [ ] Tweening
  - [ ] Origin
  - [ ] Advanced 
  - [ ] Background Image/Video
  - [ ] Keyframe Control
- [x] Timing
  - [ ] Basic Timing Wizard
  - [x] BPM
  - [x] Offset
  - [x] Slider Velocity
  - [ ] Slider Tick Rate
  - [x] Timing Setup Panel
- [ ] Song Setup
  - [ ] General
  - [ ] Difficulty
  - [ ] Audio
  - [ ] Colours
  - [ ] Design
  - [ ] Advanced

## osu!theme Browser

(?)

## Social Browser

- [x] Search bar
- [x] Sorting Style
- [x] Player Group selector (e.g. Friends)
- [ ] Player sorting (e.g. Rank, Name)
- [x] User Panels
- [x] Basic Profile Overlays
- [ ] Player Options (?)

## Chart Listing

(?)

### Chart Info

(?)

## Player

- [x] Health bar
- [x] Progress bar
- [x] Combo
- [x] Score
- [x] Pause screen
- [x] Skip button
- [x] Hitsounds
- [x] Failing screen
- [x] Break overlay
- [ ] Mini-Scoreboard
- [x] Visual Settings (?)

## Localization system

- [ ] Implementation

## Replay

- [x] Replay playback
- [ ] Maintenance buttons
  - [ ] Playback
  - [ ] Collections
  - [ ] Discussion
  - [ ] End Replay
- [x] Rewinding time in replays

**Comment by peppy** [comment]
Should probably add a `Mods` section with each mod's implementation status listed. Should has sub-items for each ruleset (game mode) in cases where the behaviour changes.

**Comment by TPGPL** [comment]
Updated.

**Comment by TPGPL** [comment]
Updated

**Comment by TPGPL** [comment]
Added a `Break overlay` point in Player header

**Comment by peppy** [comment]
marked off accuracy/scoring as these are implemented using a standardised implementation across all rulesets and will continue to be iterated towards release.

**Comment by UselessToucan** [comment]
1. Are there any guidelines for implementing Visual Settings?
![screenshot275](https://user-images.githubusercontent.com/22450664/31861906-db900948-b73d-11e7-8ea2-c56cd554f0bf.png)

2. What about seasonal backgrounds? Do we need them? If yes, are there any guidelines for implementing it?
![screenshot277](https://user-images.githubusercontent.com/22450664/31861931-2c867b7a-b73e-11e7-8247-cb1bb9cd0193.png)

**Comment by jeffswt** [comment]
@TPGPL osu!mania layout is already implemented in keyboard bindings.

**Comment by peppy** [comment]
✅  Rewinding time in replays
✅ Break overlay
✅ Basic Profile Overlays

**Comment by Hubza** [comment]
Is this still actively updated?

**Comment by peppy** [comment]
Updated

**Comment by iiSaLMaN** [comment]
✅ Scoreboards->Mods

**Comment by lunafreya** [comment]
Better nudge this issue to quickly remind everyone of what's left to do, to get the new o!client up to speed against the legacy o!client.

**Comment by swoolcock** [comment]
> Better nudge this issue to quickly remind everyone of what's left to do, to get the new o!client up to speed against the legacy o!client.

Please don't add "bump" comments.  We will manage issue priorities ourselves.

**Comment by peppy** [comment]
Going to close this one. We should open issues for remaining tasks (if deemed required for live).
